version: '2'

services:
  health-checker-db:
    image: mysql:latest
    container_name: health-checker-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
